/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include"lcd.h"
#include"ultra.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

char str[16];

int main(void)
{
    LcdInit();            // Initialize the I2C LCD
    Ultra_Init();         // Initialize ultrasonic sensor

    while (1)
    {
        uint32_t distance = Get_Distance_Cm();      // Get distance
        sprintf(str, "Dist: %2lu cm", distance);    // Format string

        LcdWriteByte(LCD_CMD, LCD_CLEAR);           // Clear LCD
        LcdPuts(LCD_LINE1, "Ultrasonic:");
        LcdPuts(LCD_LINE2, str);                    // Show distance

        DelayMs(500);   // Delay between readings
    }
}
